# Generated by Django 2.0.13 on 2019-04-10 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190410_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='age',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
