# Generated by Django 2.0.13 on 2019-04-10 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_document_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='gender',
            field=models.CharField(blank=True, max_length=1),
        ),
    ]
