# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-14 00:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='remark',
        ),
        migrations.AddField(
            model_name='file',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='file',
            name='gender',
            field=models.BooleanField(default=False),
        ),
    ]
