# Generated by Django 2.2.1 on 2019-05-26 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='idade',
        ),
    ]
