# Generated by Django 2.2.1 on 2019-05-27 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_cliente_idade'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='imagem',
            field=models.ImageField(blank=True, max_length=255, upload_to='pictures/%Y/%m/%d/'),
        ),
    ]
