# Generated by Django 2.2.1 on 2019-05-27 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_cliente_imagem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='endereco',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='imagem',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='idade',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='nome',
        ),
    ]
