# Generated by Django 2.2.1 on 2019-06-08 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_cliente_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='image',
            field=models.ImageField(blank=True, max_length=255, upload_to='clientes/pictures/%Y/%m/%d/'),
        ),
    ]
