# Generated by Django 2.2.1 on 2019-06-17 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_xpto'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cliente',
            new_name='Image',
        ),
    ]
